spring.config.import=optional:file:.env[.properties]

spring.application.name=api-rest
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=586E3272357538782F413F4428472B4B6250655368566B597033733676397924